apiVersion: v1
kind: Service
metadata:
  name: {{ clusterName }}-nodeport
  namespace: {{ namespace }}
spec:
  selector:
    app: vcluster #{{ shortClusterName }}#vcluster
    release: {{ clusterName }}
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: {{ nodePort }}
      protocol: TCP
  type: NodePort